export const states = [
	{
		name: "Telangana",
		districts: [
			"Adilabad",
			"Bhadradri Kothagudem",
			"Hanumakonda",
			"Hyderabad",
			"Jagtial",
			"Jangoan",
			"Jayashankar Bhupalpalli",
			"Jogulamba Gadwal",
			"Kamareddy",
			"Karimnagar",
			"Khammam",
			"Kumuram Bheem (Asifabad)",
			"Mahabubabad",
			"Mahabubnagar",
			"Mancherial",
			"Medak",
			"Medchal-Malkajigiri",
			"Mulug",
			"Nagarkurnool",
			"Nalgonda",
			"Narayanpet",
			"Nirmal",
			"Nizamabad",
			"Peddapalli",
			"Rajanna Sircilla",
			"Rangareddy",
			"Sangareddy",
			"Siddipet",
			"Suryapet",
			"Vikarabad",
			"Wanaparthy",
			"Warangal",
			"Yadadri Bhuvanagiri",
		],
	},
];
